# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CarTheme' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CarTheme
    pod 'RxSwift'
    pod 'RxCocoa'
    pod 'Kingfisher'
    pod 'Moya'

end
